using System.Collections.Generic;

namespace nor0x.Playwright.BrowserDownloader;
public static class Constants
{
    public static string HostedBrowsersJson = "https://raw.githubusercontent.com/nor0x/Playwright.BrowserDownloader/main/Playwright.BrowserDownloader/browsers.json";

    //from playwright/lib/server/registry/index.js
    public static Dictionary<string, Dictionary<string, string>> Paths = new() {
    {
      "chromium",
      new Dictionary < string,
      string > {
        ["<unknown>"] = null,
        ["ubuntu18.04-x64"] = null,
        ["ubuntu20.04-x64"] = "builds/chromium/{0}/chromium-linux.zip",
        ["ubuntu22.04-x64"] = "builds/chromium/{0}/chromium-linux.zip",
        ["ubuntu18.04-arm64"] = null,
        ["ubuntu20.04-arm64"] = "builds/chromium/{0}/chromium-linux-arm64.zip",
        ["ubuntu22.04-arm64"] = "builds/chromium/{0}/chromium-linux-arm64.zip",
        ["debian11-x64"] = "builds/chromium/{0}/chromium-linux.zip",
        ["debian11-arm64"] = "builds/chromium/{0}/chromium-linux-arm64.zip",
        ["debian12-x64"] = "builds/chromium/{0}/chromium-linux.zip",
        ["debian12-arm64"] = "builds/chromium/{0}/chromium-linux-arm64.zip",
        ["mac10.13"] = "builds/chromium/{0}/chromium-mac.zip",
        ["mac10.14"] = "builds/chromium/{0}/chromium-mac.zip",
        ["mac10.15"] = "builds/chromium/{0}/chromium-mac.zip",
        ["mac11"] = "builds/chromium/{0}/chromium-mac.zip",
        ["mac11-arm64"] = "builds/chromium/{0}/chromium-mac-arm64.zip",
        ["mac12"] = "builds/chromium/{0}/chromium-mac.zip",
        ["mac12-arm64"] = "builds/chromium/{0}/chromium-mac-arm64.zip",
        ["mac13"] = "builds/chromium/{0}/chromium-mac.zip",
        ["mac13-arm64"] = "builds/chromium/{0}/chromium-mac-arm64.zip",
        ["mac14"] = "builds/chromium/{0}/chromium-mac.zip",
        ["mac14-arm64"] = "builds/chromium/{0}/chromium-mac-arm64.zip",
        ["win64"] = "builds/chromium/{0}/chromium-win64.zip",
      }
    }, {
      "chromium-tip-of-tree",
      new Dictionary < string,
      string > {
        ["<unknown>"] = null,
        ["ubuntu18.04-x64"] = null,
        ["ubuntu20.04-x64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-linux.zip",
        ["ubuntu22.04-x64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-linux.zip",
        ["ubuntu18.04-arm64"] = null,
        ["ubuntu20.04-arm64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-linux-arm64.zip",
        ["ubuntu22.04-arm64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-linux-arm64.zip",
        ["debian11-x64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-linux.zip",
        ["debian11-arm64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-linux-arm64.zip",
        ["debian12-x64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-linux.zip",
        ["debian12-arm64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-linux-arm64.zip",
        ["mac10.13"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-mac.zip",
        ["mac10.14"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-mac.zip",
        ["mac10.15"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-mac.zip",
        ["mac11"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-mac.zip",
        ["mac11-arm64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-mac-arm64.zip",
        ["mac12"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-mac.zip",
        ["mac12-arm64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-mac-arm64.zip",
        ["mac13"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-mac.zip",
        ["mac13-arm64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-mac-arm64.zip",
        ["mac14"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-mac.zip",
        ["mac14-arm64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-mac-arm64.zip",
        ["win64"] = "builds/chromium-tip-of-tree/{0}/chromium-tip-of-tree-win64.zip",
      }
    }, {
      "firefox",
      new Dictionary < string,
      string > {
        ["<unknown>"] = null,
        ["ubuntu18.04-x64"] = null,
        ["ubuntu20.04-x64"] = "builds/firefox/{0}/firefox-ubuntu-20.04.zip",
        ["ubuntu22.04-x64"] = "builds/firefox/{0}/firefox-ubuntu-22.04.zip",
        ["ubuntu18.04-arm64"] = null,
        ["ubuntu20.04-arm64"] = "builds/firefox/{0}/firefox-ubuntu-20.04-arm64.zip",
        ["ubuntu22.04-arm64"] = "builds/firefox/{0}/firefox-ubuntu-22.04-arm64.zip",
        ["debian11-x64"] = "builds/firefox/{0}/firefox-debian-11.zip",
        ["debian11-arm64"] = "builds/firefox/{0}/firefox-debian-11-arm64.zip",
        ["debian12-x64"] = "builds/firefox/{0}/firefox-debian-12.zip",
        ["debian12-arm64"] = "builds/firefox/{0}/firefox-debian-12-arm64.zip",
        ["mac10.13"] = "builds/firefox/{0}/firefox-mac-13.zip",
        ["mac10.14"] = "builds/firefox/{0}/firefox-mac-13.zip",
        ["mac10.15"] = "builds/firefox/{0}/firefox-mac-13.zip",
        ["mac11"] = "builds/firefox/{0}/firefox-mac-13.zip",
        ["mac11-arm64"] = "builds/firefox/{0}/firefox-mac-13-arm64.zip",
        ["mac12"] = "builds/firefox/{0}/firefox-mac-13.zip",
        ["mac12-arm64"] = "builds/firefox/{0}/firefox-mac-13-arm64.zip",
        ["mac13"] = "builds/firefox/{0}/firefox-mac-13.zip",
        ["mac13-arm64"] = "builds/firefox/{0}/firefox-mac-13-arm64.zip",
        ["mac14"] = "builds/firefox/{0}/firefox-mac-13.zip",
        ["mac14-arm64"] = "builds/firefox/{0}/firefox-mac-13-arm64.zip",
        ["win64"] = "builds/firefox/{0}/firefox-win64.zip",
      }
    }, {
      "firefox-beta",
      new Dictionary < string,
      string > {
        ["<unknown>"] = null,
        ["ubuntu18.04-x64"] = null,
        ["ubuntu20.04-x64"] = "builds/firefox-beta/{0}/firefox-beta-ubuntu-20.04.zip",
        ["ubuntu22.04-x64"] = "builds/firefox-beta/{0}/firefox-beta-ubuntu-22.04.zip",
        ["ubuntu18.04-arm64"] = null,
        ["ubuntu20.04-arm64"] = null,
        ["ubuntu22.04-arm64"] = "builds/firefox-beta/{0}/firefox-beta-ubuntu-22.04-arm64.zip",
        ["debian11-x64"] = "builds/firefox-beta/{0}/firefox-beta-debian-11.zip",
        ["debian11-arm64"] = "builds/firefox-beta/{0}/firefox-beta-debian-11-arm64.zip",
        ["debian12-x64"] = "builds/firefox-beta/{0}/firefox-beta-debian-12.zip",
        ["debian12-arm64"] = "builds/firefox-beta/{0}/firefox-beta-debian-12-arm64.zip",
        ["mac10.13"] = "builds/firefox-beta/{0}/firefox-beta-mac-13.zip",
        ["mac10.14"] = "builds/firefox-beta/{0}/firefox-beta-mac-13.zip",
        ["mac10.15"] = "builds/firefox-beta/{0}/firefox-beta-mac-13.zip",
        ["mac11"] = "builds/firefox-beta/{0}/firefox-beta-mac-13.zip",
        ["mac11-arm64"] = "builds/firefox-beta/{0}/firefox-beta-mac-13-arm64.zip",
        ["mac12"] = "builds/firefox-beta/{0}/firefox-beta-mac-13.zip",
        ["mac12-arm64"] = "builds/firefox-beta/{0}/firefox-beta-mac-13-arm64.zip",
        ["mac13"] = "builds/firefox-beta/{0}/firefox-beta-mac-13.zip",
        ["mac13-arm64"] = "builds/firefox-beta/{0}/firefox-beta-mac-13-arm64.zip",
        ["mac14"] = "builds/firefox-beta/{0}/firefox-beta-mac-13.zip",
        ["mac14-arm64"] = "builds/firefox-beta/{0}/firefox-beta-mac-13-arm64.zip",
        ["win64"] = "builds/firefox-beta/{0}/firefox-beta-win64.zip",
      }
    }, {
      "firefox-asan",
      new Dictionary < string,
      string > {
        ["<unknown>"] = null,
        ["ubuntu18.04-x64"] = null,
        ["ubuntu20.04-x64"] = null,
        ["ubuntu22.04-x64"] = "builds/firefox/{0}/firefox-asan-ubuntu-22.04.zip",
        ["ubuntu18.04-arm64"] = null,
        ["ubuntu20.04-arm64"] = null,
        ["ubuntu22.04-arm64"] = null,
        ["debian11-x64"] = null,
        ["debian11-arm64"] = null,
        ["debian12-x64"] = null,
        ["debian12-arm64"] = null,
        ["mac10.13"] = "builds/firefox/{0}/firefox-asan-mac-13.zip",
        ["mac10.14"] = "builds/firefox/{0}/firefox-asan-mac-13.zip",
        ["mac10.15"] = "builds/firefox/{0}/firefox-asan-mac-13.zip",
        ["mac11"] = "builds/firefox/{0}/firefox-asan-mac-13.zip",
        ["mac11-arm64"] = null,
        ["mac12"] = "builds/firefox/{0}/firefox-asan-mac-13.zip",
        ["mac12-arm64"] = null,
        ["mac13"] = "builds/firefox/{0}/firefox-asan-mac-13.zip",
        ["mac13-arm64"] = null,
        ["mac14"] = "builds/firefox/{0}/firefox-asan-mac-13.zip",
        ["mac14-arm64"] = null,
        ["win64"] = null,
      }
    }, {
      "webkit",
      new Dictionary < string,
      string > {
        ["<unknown>"] = null,
        ["ubuntu18.04-x64"] = null,
        ["ubuntu20.04-x64"] = "builds/webkit/{0}/webkit-ubuntu-20.04.zip",
        ["ubuntu22.04-x64"] = "builds/webkit/{0}/webkit-ubuntu-22.04.zip",
        ["ubuntu18.04-arm64"] = null,
        ["ubuntu20.04-arm64"] = "builds/webkit/{0}/webkit-ubuntu-20.04-arm64.zip",
        ["ubuntu22.04-arm64"] = "builds/webkit/{0}/webkit-ubuntu-22.04-arm64.zip",
        ["debian11-x64"] = "builds/webkit/{0}/webkit-debian-11.zip",
        ["debian11-arm64"] = "builds/webkit/{0}/webkit-debian-11-arm64.zip",
        ["debian12-x64"] = "builds/webkit/{0}/webkit-debian-12.zip",
        ["debian12-arm64"] = "builds/webkit/{0}/webkit-debian-12-arm64.zip",
        ["mac10.13"] = null,
        ["mac10.14"] = "builds/deprecated-webkit-mac-10.14/{0}/deprecated-webkit-mac-10.14.zip",
        ["mac10.15"] = "builds/deprecated-webkit-mac-10.15/{0}/deprecated-webkit-mac-10.15.zip",
        ["mac11"] = "builds/webkit/{0}/webkit-mac-11.zip",
        ["mac11-arm64"] = "builds/webkit/{0}/webkit-mac-11-arm64.zip",
        ["mac12"] = "builds/webkit/{0}/webkit-mac-12.zip",
        ["mac12-arm64"] = "builds/webkit/{0}/webkit-mac-12-arm64.zip",
        ["mac13"] = "builds/webkit/{0}/webkit-mac-13.zip",
        ["mac13-arm64"] = "builds/webkit/{0}/webkit-mac-13-arm64.zip",
        ["mac14"] = "builds/webkit/{0}/webkit-mac-14.zip",
        ["mac14-arm64"] = "builds/webkit/{0}/webkit-mac-14-arm64.zip",
        ["win64"] = "builds/webkit/{0}/webkit-win64.zip",
      }
    }, {
      "ffmpeg",
      new Dictionary < string,
      string > {
        ["<unknown>"] = null,
        ["ubuntu18.04-x64"] = null,
        ["ubuntu20.04-x64"] = "builds/ffmpeg/{0}/ffmpeg-linux.zip",
        ["ubuntu22.04-x64"] = "builds/ffmpeg/{0}/ffmpeg-linux.zip",
        ["ubuntu18.04-arm64"] = null,
        ["ubuntu20.04-arm64"] = "builds/ffmpeg/{0}/ffmpeg-linux-arm64.zip",
        ["ubuntu22.04-arm64"] = "builds/ffmpeg/{0}/ffmpeg-linux-arm64.zip",
        ["debian11-x64"] = "builds/ffmpeg/{0}/ffmpeg-linux.zip",
        ["debian11-arm64"] = "builds/ffmpeg/{0}/ffmpeg-linux-arm64.zip",
        ["debian12-x64"] = "builds/ffmpeg/{0}/ffmpeg-linux.zip",
        ["debian12-arm64"] = "builds/ffmpeg/{0}/ffmpeg-linux-arm64.zip",
        ["mac10.13"] = "builds/ffmpeg/{0}/ffmpeg-mac.zip",
        ["mac10.14"] = "builds/ffmpeg/{0}/ffmpeg-mac.zip",
        ["mac10.15"] = "builds/ffmpeg/{0}/ffmpeg-mac.zip",
        ["mac11"] = "builds/ffmpeg/{0}/ffmpeg-mac.zip",
        ["mac11-arm64"] = "builds/ffmpeg/{0}/ffmpeg-mac-arm64.zip",
        ["mac12"] = "builds/ffmpeg/{0}/ffmpeg-mac.zip",
        ["mac12-arm64"] = "builds/ffmpeg/{0}/ffmpeg-mac-arm64.zip",
        ["mac13"] = "builds/ffmpeg/{0}/ffmpeg-mac.zip",
        ["mac13-arm64"] = "builds/ffmpeg/{0}/ffmpeg-mac-arm64.zip",
        ["mac14"] = "builds/ffmpeg/{0}/ffmpeg-mac.zip",
        ["mac14-arm64"] = "builds/ffmpeg/{0}/ffmpeg-mac-arm64.zip",
        ["win64"] = "builds/ffmpeg/{0}/ffmpeg-win64.zip",
      }
    }, {
      "android",
      new Dictionary < string,
      string > {
        ["<unknown>"] = "builds/android/{0}/android.zip",
        ["ubuntu18.04-x64"] = null,
        ["ubuntu20.04-x64"] = "builds/android/{0}/android.zip",
        ["ubuntu22.04-x64"] = "builds/android/{0}/android.zip",
        ["ubuntu18.04-arm64"] = null,
        ["ubuntu20.04-arm64"] = "builds/android/{0}/android.zip",
        ["ubuntu22.04-arm64"] = "builds/android/{0}/android.zip",
        ["debian11-x64"] = "builds/android/{0}/android.zip",
        ["debian11-arm64"] = "builds/android/{0}/android.zip",
        ["debian12-x64"] = "builds/android/{0}/android.zip",
        ["debian12-arm64"] = "builds/android/{0}/android.zip",
        ["mac10.13"] = "builds/android/{0}/android.zip",
        ["mac10.14"] = "builds/android/{0}/android.zip",
        ["mac10.15"] = "builds/android/{0}/android.zip",
        ["mac11"] = "builds/android/{0}/android.zip",
        ["mac11-arm64"] = "builds/android/{0}/android.zip",
        ["mac12"] = "builds/android/{0}/android.zip",
        ["mac12-arm64"] = "builds/android/{0}/android.zip",
        ["mac13"] = "builds/android/{0}/android.zip",
        ["mac13-arm64"] = "builds/android/{0}/android.zip",
        ["mac14"] = "builds/android/{0}/android.zip",
        ["mac14-arm64"] = "builds/android/{0}/android.zip",
        ["win64"] = "builds/android/{0}/android.zip",
      }
    }
  };
}

public enum Platform
{
    Unknown,
    Ubuntu1804x64,
    Ubuntu2004x64,
    Ubuntu2204x64,
    Ubuntu1804arm64,
    Ubuntu2004arm64,
    Ubuntu2204arm64,
    Debian11x64,
    Debian11arm64,
    Debian12x64,
    Debian12arm64,
    Mac1013,
    Mac1014,
    Mac1015,
    Mac11,
    Mac11arm64,
    Mac12,
    Mac12arm64,
    Mac13,
    Mac13arm64,
    Mac14,
    Mac14arm64,
    Win64
}